theme: jekyll-theme-cayman
title: HackforPlayDocs
lang: ja
google_analytics: UA-113487422-4
code_url: https://github.com/hackforplay/common
twitter:
  username: hackforplay
  card: summary
facebook:
  app_id: 2762772990425604
